import Head from "next/head";
import Image from "next/image";
import Payment from "../components/PaymentButton";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </Head>

      <h1>Hello world</h1>
      <Payment amount={500} country="India" />
    </div>
  );
}
